version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: seizure-stroke-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models
      - ./outputs:/app/outputs
    restart: always
    environment:
      - PYTHONUNBUFFERED=1
      - S3_LOG_BUCKET=seizure-prediction-logs
